
version: "1.2.0"

persistenceReplicas: 1
persistenceCpu: 1000m
persistenceMemory: 1000Mi

webuiReplicas: 1
webuiCpu: 1000m
webuiMemory: 1000Mi

recommenderReplicas: 1
recommenderCpu: 1000m
recommenderMemory: 1000Mi

registryReplicas: 1
registryCpu: 500m
registryMemory: 1000Mi

dbReplicas: 1
dbCpu: 1000m
dbMemory: 1000Mi

authReplicas: 1
authCpu: 1000m
authMemory: 1000Mi


imageReplicas: 1
imageCpu: 1000m
imageMemory: 1000Mi



