# Example Network CRD
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: NetworkTopology
metadata:
  name: net-topology-test
  namespace: default
spec:
  configmapName: "netperf-metrics"
  weights:
    # Region label: "topology.kubernetes.io/region"
    # Zone Label:   "topology.kubernetes.io/zone"
    # 1 Regions:  belgium
    # 16 Zones:
    - name: "UserDefined"
      topologyList: # Define weights between regions or between zones
        - topologyKey: "topology.kubernetes.io/region" # region costs
          originList:
            - origin: "belgium"
              costList:
        - topologyKey: "topology.kubernetes.io/zone" # zone costs
          originList:
            - origin: "z1" # consider z1 for master node
              costList:
            - origin: "z2"
              costList:
            - origin: "z3"
              costList:
            - origin: "z4"
              costList:
            - origin: "z5"
              costList:



