apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-plugin-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "" # deploy scheduler-plugins on master node
      containers:
        - image: jpedro1992/kube-scheduler:kubecon # or localhost:5000/scheduler-plugins/kube-scheduler:latest if builded locally
          #imagePullPolicy: Never
          command:
          - /bin/kube-scheduler
          - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
          - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
          - --config=/etc/kubernetes/sched-cc.yaml # place config on this location!
          - -v=9
          name: scheduler-plugin
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /etc/kubernetes
            name: etckubernetes
      hostNetwork: false
      hostPID: false
      volumes:
      - hostPath:
          path: /etc/kubernetes/
          type: Directory
        name: etckubernetes

